// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/HarryWang29/echo_mind/config"
	"github.com/HarryWang29/echo_mind/internal/application/sync"
	"github.com/HarryWang29/echo_mind/internal/domain/account_info"
	"github.com/HarryWang29/echo_mind/internal/infra/db/repo"
)

// Injectors from wire.go:

func InjectAll() (*sync_db.App, error) {
	configConfig := config.NewConfig()
	wechatConfig := config.GetWechatConfig(configConfig)
	dataSourceConfig := config.GetDataSourceConfig(configConfig)
	db, err := repo.NewRepo(dataSourceConfig)
	if err != nil {
		return nil, err
	}
	v := repo.GetOptions()
	query := repo.Use(db, v...)
	accountInfo, err := account_info.NewAccountInfo(query)
	if err != nil {
		return nil, err
	}
	app, err := sync_db.NewApp(wechatConfig, query, accountInfo)
	if err != nil {
		return nil, err
	}
	return app, nil
}
