// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAccountInfo = "account_info"

// AccountInfo mapped from table <account_info>
type AccountInfo struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserName string `gorm:"column:user_name" json:"user_name"`
	Nickname string `gorm:"column:nickname" json:"nickname"`
	Hash     string `gorm:"column:hash;not null" json:"hash"`
}

// TableName AccountInfo's table name
func (*AccountInfo) TableName() string {
	return TableNameAccountInfo
}
