// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGroupContactPerson = "group_contact_person"

// GroupContactPerson mapped from table <group_contact_person>
type GroupContactPerson struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AccountID    int64          `gorm:"column:account_id;not null;comment:账号id" json:"account_id"`         // 账号id
	UserName     string         `gorm:"column:user_name;not null;comment:用户名称" json:"user_name"`           // 用户名称
	Nickname     string         `gorm:"column:nickname;not null;comment:昵称" json:"nickname"`               // 昵称
	Remark       string         `gorm:"column:remark;not null;comment:备注" json:"remark"`                   // 备注
	HeadImgURL   string         `gorm:"column:head_img_url;not null;comment:头像" json:"head_img_url"`       // 头像
	HeadHdImgURL string         `gorm:"column:head_hd_img_url;not null;comment:头像" json:"head_hd_img_url"` // 头像
	Sex          int32          `gorm:"column:sex;not null;comment:性别" json:"sex"`                         // 性别
	Type         int32          `gorm:"column:type;not null;comment:类型" json:"type"`                       // 类型
	DbName       string         `gorm:"column:db_name;not null;comment:数据库名称" json:"db_name"`              // 数据库名称
	Status       bool           `gorm:"column:status;not null;default:1;comment:状态" json:"status"`         // 状态
	Hash         string         `gorm:"column:hash;not null" json:"hash"`
	CreatedAt    time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName GroupContactPerson's table name
func (*GroupContactPerson) TableName() string {
	return TableNameGroupContactPerson
}
