// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGroupUserRelation = "group_user_relation"

// GroupUserRelation mapped from table <group_user_relation>
type GroupUserRelation struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AccountID int64  `gorm:"column:account_id;not null;comment:账号id" json:"account_id"` // 账号id
	UserName  string `gorm:"column:user_name" json:"user_name"`
	GroupName string `gorm:"column:group_name" json:"group_name"`
}

// TableName GroupUserRelation's table name
func (*GroupUserRelation) TableName() string {
	return TableNameGroupUserRelation
}
