// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMessage = "message"

// Message mapped from table <message>
type Message struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AccountID   int64  `gorm:"column:account_id;not null;comment:账号id" json:"account_id"` // 账号id
	Hash        string `gorm:"column:hash;not null" json:"hash"`
	LocalID     int64  `gorm:"column:local_id;not null" json:"local_id"`
	SvrID       int64  `gorm:"column:svr_id;not null;comment:服务器id" json:"svr_id"`          // 服务器id
	CreateTime  int64  `gorm:"column:create_time;not null;comment:消息时间" json:"create_time"` // 消息时间
	Content     string `gorm:"column:content;not null;comment:正文" json:"content"`           // 正文
	Translate   string `gorm:"column:translate;not null" json:"translate"`
	Status      int64  `gorm:"column:status;not null;comment:状态" json:"status"`             // 状态
	ImgStatus   int64  `gorm:"column:img_status;not null;comment:图片状态" json:"img_status"`   // 图片状态
	MessageType int32  `gorm:"column:message_type;not null;comment:类型" json:"message_type"` // 类型
	Des         bool   `gorm:"column:des;not null" json:"des"`
	Source      string `gorm:"column:source;not null" json:"source"`
	VoiceText   string `gorm:"column:voice_text;not null" json:"voice_text"`
	Seq         int64  `gorm:"column:seq;not null" json:"seq"`
	DbName      string `gorm:"column:db_name;not null;comment:数据库名称" json:"db_name"` // 数据库名称
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
