// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSessionAbstract = "session_abstract"

// SessionAbstract mapped from table <session_abstract>
type SessionAbstract struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AccountID   int64          `gorm:"column:account_id;not null;comment:账号id" json:"account_id"` // 账号id
	UserName    string         `gorm:"column:user_name;not null" json:"user_name"`
	UnreadCount int32          `gorm:"column:unread_count;not null" json:"unread_count"`
	LastTime    int64          `gorm:"column:last_time;not null" json:"last_time"`
	CreatedAt   time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName SessionAbstract's table name
func (*SessionAbstract) TableName() string {
	return TableNameSessionAbstract
}
