// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSessionAbstract = "SessionAbstract"

// SessionAbstract mapped from table <SessionAbstract>
type SessionAbstract struct {
	MNsUserName          string `gorm:"column:m_nsUserName;primaryKey" json:"m_nsUserName"`
	MUUnReadCount        int32  `gorm:"column:m_uUnReadCount" json:"m_uUnReadCount"`
	MBShowUnReadAsRedDot int32  `gorm:"column:m_bShowUnReadAsRedDot" json:"m_bShowUnReadAsRedDot"`
	MBMarkUnread         int32  `gorm:"column:m_bMarkUnread" json:"m_bMarkUnread"`
	MULastTime           int32  `gorm:"column:m_uLastTime" json:"m_uLastTime"`
	StrRes1              string `gorm:"column:strRes1" json:"strRes1"`
	StrRes2              string `gorm:"column:strRes2" json:"strRes2"`
	StrRes3              string `gorm:"column:strRes3" json:"strRes3"`
	IntRes1              int32  `gorm:"column:intRes1" json:"intRes1"`
	IntRes2              int32  `gorm:"column:intRes2" json:"intRes2"`
	IntRes3              int32  `gorm:"column:intRes3" json:"intRes3"`
	PackedMMSessionInfo  []byte `gorm:"column:_packed_MMSessionInfo" json:"_packed_MMSessionInfo"`
}

// TableName SessionAbstract's table name
func (*SessionAbstract) TableName() string {
	return TableNameSessionAbstract
}
