// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package group

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HarryWang29/echo_mind/internal/infra/db/sqlite/model"
)

func newGroupContact(db *gorm.DB, opts ...gen.DOOption) groupContact {
	_groupContact := groupContact{}

	_groupContact.groupContactDo.UseDB(db, opts...)
	_groupContact.groupContactDo.UseModel(&model.GroupContact{})

	tableName := _groupContact.groupContactDo.TableName()
	_groupContact.ALL = field.NewAsterisk(tableName)
	_groupContact.MNsUsrName = field.NewString(tableName, "m_nsUsrName")
	_groupContact.MUIConType = field.NewInt32(tableName, "m_uiConType")
	_groupContact.Nickname = field.NewString(tableName, "nickname")
	_groupContact.MNsFullPY = field.NewString(tableName, "m_nsFullPY")
	_groupContact.MNsShortPY = field.NewString(tableName, "m_nsShortPY")
	_groupContact.MNsRemark = field.NewString(tableName, "m_nsRemark")
	_groupContact.MNsRemarkPYFull = field.NewString(tableName, "m_nsRemarkPYFull")
	_groupContact.MNsRemarkPYShort = field.NewString(tableName, "m_nsRemarkPYShort")
	_groupContact.MUICertificationFlag = field.NewInt32(tableName, "m_uiCertificationFlag")
	_groupContact.MUISex = field.NewInt32(tableName, "m_uiSex")
	_groupContact.MUIType = field.NewInt32(tableName, "m_uiType")
	_groupContact.MNsImgStatus = field.NewString(tableName, "m_nsImgStatus")
	_groupContact.MUIImgKey = field.NewInt32(tableName, "m_uiImgKey")
	_groupContact.MNsHeadImgURL = field.NewString(tableName, "m_nsHeadImgUrl")
	_groupContact.MNsHeadHDImgURL = field.NewString(tableName, "m_nsHeadHDImgUrl")
	_groupContact.MNsHeadHDMd5 = field.NewString(tableName, "m_nsHeadHDMd5")
	_groupContact.MNsChatRoomMemList = field.NewString(tableName, "m_nsChatRoomMemList")
	_groupContact.MNsChatRoomAdminList = field.NewString(tableName, "m_nsChatRoomAdminList")
	_groupContact.MUIChatRoomStatus = field.NewInt32(tableName, "m_uiChatRoomStatus")
	_groupContact.MNsChatRoomDesc = field.NewString(tableName, "m_nsChatRoomDesc")
	_groupContact.MNsDraft = field.NewString(tableName, "m_nsDraft")
	_groupContact.MNsBrandIconURL = field.NewString(tableName, "m_nsBrandIconUrl")
	_groupContact.MNsGoogleContactName = field.NewString(tableName, "m_nsGoogleContactName")
	_groupContact.MNsAliasName = field.NewString(tableName, "m_nsAliasName")
	_groupContact.MNsEncodeUserName = field.NewString(tableName, "m_nsEncodeUserName")
	_groupContact.MUIChatRoomVersion = field.NewInt32(tableName, "m_uiChatRoomVersion")
	_groupContact.MUIChatRoomMaxCount = field.NewInt32(tableName, "m_uiChatRoomMaxCount")
	_groupContact.MUIChatRoomType = field.NewInt32(tableName, "m_uiChatRoomType")
	_groupContact.MPatSuffix = field.NewString(tableName, "m_patSuffix")
	_groupContact.RichChatRoomDesc = field.NewString(tableName, "richChatRoomDesc")
	_groupContact.PackedWCContactData = field.NewBytes(tableName, "_packed_WCContactData")
	_groupContact.OpenIMInfo = field.NewBytes(tableName, "openIMInfo")

	_groupContact.fillFieldMap()

	return _groupContact
}

type groupContact struct {
	groupContactDo

	ALL                  field.Asterisk
	MNsUsrName           field.String
	MUIConType           field.Int32
	Nickname             field.String
	MNsFullPY            field.String
	MNsShortPY           field.String
	MNsRemark            field.String
	MNsRemarkPYFull      field.String
	MNsRemarkPYShort     field.String
	MUICertificationFlag field.Int32
	MUISex               field.Int32
	MUIType              field.Int32
	MNsImgStatus         field.String
	MUIImgKey            field.Int32
	MNsHeadImgURL        field.String
	MNsHeadHDImgURL      field.String
	MNsHeadHDMd5         field.String
	MNsChatRoomMemList   field.String
	MNsChatRoomAdminList field.String
	MUIChatRoomStatus    field.Int32
	MNsChatRoomDesc      field.String
	MNsDraft             field.String
	MNsBrandIconURL      field.String
	MNsGoogleContactName field.String
	MNsAliasName         field.String
	MNsEncodeUserName    field.String
	MUIChatRoomVersion   field.Int32
	MUIChatRoomMaxCount  field.Int32
	MUIChatRoomType      field.Int32
	MPatSuffix           field.String
	RichChatRoomDesc     field.String
	PackedWCContactData  field.Bytes
	OpenIMInfo           field.Bytes

	fieldMap map[string]field.Expr
}

func (g groupContact) Table(newTableName string) *groupContact {
	g.groupContactDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g groupContact) As(alias string) *groupContact {
	g.groupContactDo.DO = *(g.groupContactDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *groupContact) updateTableName(table string) *groupContact {
	g.ALL = field.NewAsterisk(table)
	g.MNsUsrName = field.NewString(table, "m_nsUsrName")
	g.MUIConType = field.NewInt32(table, "m_uiConType")
	g.Nickname = field.NewString(table, "nickname")
	g.MNsFullPY = field.NewString(table, "m_nsFullPY")
	g.MNsShortPY = field.NewString(table, "m_nsShortPY")
	g.MNsRemark = field.NewString(table, "m_nsRemark")
	g.MNsRemarkPYFull = field.NewString(table, "m_nsRemarkPYFull")
	g.MNsRemarkPYShort = field.NewString(table, "m_nsRemarkPYShort")
	g.MUICertificationFlag = field.NewInt32(table, "m_uiCertificationFlag")
	g.MUISex = field.NewInt32(table, "m_uiSex")
	g.MUIType = field.NewInt32(table, "m_uiType")
	g.MNsImgStatus = field.NewString(table, "m_nsImgStatus")
	g.MUIImgKey = field.NewInt32(table, "m_uiImgKey")
	g.MNsHeadImgURL = field.NewString(table, "m_nsHeadImgUrl")
	g.MNsHeadHDImgURL = field.NewString(table, "m_nsHeadHDImgUrl")
	g.MNsHeadHDMd5 = field.NewString(table, "m_nsHeadHDMd5")
	g.MNsChatRoomMemList = field.NewString(table, "m_nsChatRoomMemList")
	g.MNsChatRoomAdminList = field.NewString(table, "m_nsChatRoomAdminList")
	g.MUIChatRoomStatus = field.NewInt32(table, "m_uiChatRoomStatus")
	g.MNsChatRoomDesc = field.NewString(table, "m_nsChatRoomDesc")
	g.MNsDraft = field.NewString(table, "m_nsDraft")
	g.MNsBrandIconURL = field.NewString(table, "m_nsBrandIconUrl")
	g.MNsGoogleContactName = field.NewString(table, "m_nsGoogleContactName")
	g.MNsAliasName = field.NewString(table, "m_nsAliasName")
	g.MNsEncodeUserName = field.NewString(table, "m_nsEncodeUserName")
	g.MUIChatRoomVersion = field.NewInt32(table, "m_uiChatRoomVersion")
	g.MUIChatRoomMaxCount = field.NewInt32(table, "m_uiChatRoomMaxCount")
	g.MUIChatRoomType = field.NewInt32(table, "m_uiChatRoomType")
	g.MPatSuffix = field.NewString(table, "m_patSuffix")
	g.RichChatRoomDesc = field.NewString(table, "richChatRoomDesc")
	g.PackedWCContactData = field.NewBytes(table, "_packed_WCContactData")
	g.OpenIMInfo = field.NewBytes(table, "openIMInfo")

	g.fillFieldMap()

	return g
}

func (g *groupContact) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *groupContact) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 32)
	g.fieldMap["m_nsUsrName"] = g.MNsUsrName
	g.fieldMap["m_uiConType"] = g.MUIConType
	g.fieldMap["nickname"] = g.Nickname
	g.fieldMap["m_nsFullPY"] = g.MNsFullPY
	g.fieldMap["m_nsShortPY"] = g.MNsShortPY
	g.fieldMap["m_nsRemark"] = g.MNsRemark
	g.fieldMap["m_nsRemarkPYFull"] = g.MNsRemarkPYFull
	g.fieldMap["m_nsRemarkPYShort"] = g.MNsRemarkPYShort
	g.fieldMap["m_uiCertificationFlag"] = g.MUICertificationFlag
	g.fieldMap["m_uiSex"] = g.MUISex
	g.fieldMap["m_uiType"] = g.MUIType
	g.fieldMap["m_nsImgStatus"] = g.MNsImgStatus
	g.fieldMap["m_uiImgKey"] = g.MUIImgKey
	g.fieldMap["m_nsHeadImgUrl"] = g.MNsHeadImgURL
	g.fieldMap["m_nsHeadHDImgUrl"] = g.MNsHeadHDImgURL
	g.fieldMap["m_nsHeadHDMd5"] = g.MNsHeadHDMd5
	g.fieldMap["m_nsChatRoomMemList"] = g.MNsChatRoomMemList
	g.fieldMap["m_nsChatRoomAdminList"] = g.MNsChatRoomAdminList
	g.fieldMap["m_uiChatRoomStatus"] = g.MUIChatRoomStatus
	g.fieldMap["m_nsChatRoomDesc"] = g.MNsChatRoomDesc
	g.fieldMap["m_nsDraft"] = g.MNsDraft
	g.fieldMap["m_nsBrandIconUrl"] = g.MNsBrandIconURL
	g.fieldMap["m_nsGoogleContactName"] = g.MNsGoogleContactName
	g.fieldMap["m_nsAliasName"] = g.MNsAliasName
	g.fieldMap["m_nsEncodeUserName"] = g.MNsEncodeUserName
	g.fieldMap["m_uiChatRoomVersion"] = g.MUIChatRoomVersion
	g.fieldMap["m_uiChatRoomMaxCount"] = g.MUIChatRoomMaxCount
	g.fieldMap["m_uiChatRoomType"] = g.MUIChatRoomType
	g.fieldMap["m_patSuffix"] = g.MPatSuffix
	g.fieldMap["richChatRoomDesc"] = g.RichChatRoomDesc
	g.fieldMap["_packed_WCContactData"] = g.PackedWCContactData
	g.fieldMap["openIMInfo"] = g.OpenIMInfo
}

func (g groupContact) clone(db *gorm.DB) groupContact {
	g.groupContactDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g groupContact) replaceDB(db *gorm.DB) groupContact {
	g.groupContactDo.ReplaceDB(db)
	return g
}

type groupContactDo struct{ gen.DO }

type IGroupContactDo interface {
	gen.SubQuery
	Debug() IGroupContactDo
	WithContext(ctx context.Context) IGroupContactDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGroupContactDo
	WriteDB() IGroupContactDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGroupContactDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGroupContactDo
	Not(conds ...gen.Condition) IGroupContactDo
	Or(conds ...gen.Condition) IGroupContactDo
	Select(conds ...field.Expr) IGroupContactDo
	Where(conds ...gen.Condition) IGroupContactDo
	Order(conds ...field.Expr) IGroupContactDo
	Distinct(cols ...field.Expr) IGroupContactDo
	Omit(cols ...field.Expr) IGroupContactDo
	Join(table schema.Tabler, on ...field.Expr) IGroupContactDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGroupContactDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGroupContactDo
	Group(cols ...field.Expr) IGroupContactDo
	Having(conds ...gen.Condition) IGroupContactDo
	Limit(limit int) IGroupContactDo
	Offset(offset int) IGroupContactDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGroupContactDo
	Unscoped() IGroupContactDo
	Create(values ...*model.GroupContact) error
	CreateInBatches(values []*model.GroupContact, batchSize int) error
	Save(values ...*model.GroupContact) error
	First() (*model.GroupContact, error)
	Take() (*model.GroupContact, error)
	Last() (*model.GroupContact, error)
	Find() ([]*model.GroupContact, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GroupContact, err error)
	FindInBatches(result *[]*model.GroupContact, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GroupContact) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGroupContactDo
	Assign(attrs ...field.AssignExpr) IGroupContactDo
	Joins(fields ...field.RelationField) IGroupContactDo
	Preload(fields ...field.RelationField) IGroupContactDo
	FirstOrInit() (*model.GroupContact, error)
	FirstOrCreate() (*model.GroupContact, error)
	FindByPage(offset int, limit int) (result []*model.GroupContact, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGroupContactDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	GetByID(id int) (result model.GroupContact, err error)
}

// SELECT * FROM @@table WHERE id=@id
func (g groupContactDo) GetByID(id int) (result model.GroupContact, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("SELECT * FROM GroupContact WHERE id=? ")

	var executeSQL *gorm.DB
	executeSQL = g.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (g groupContactDo) Debug() IGroupContactDo {
	return g.withDO(g.DO.Debug())
}

func (g groupContactDo) WithContext(ctx context.Context) IGroupContactDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g groupContactDo) ReadDB() IGroupContactDo {
	return g.Clauses(dbresolver.Read)
}

func (g groupContactDo) WriteDB() IGroupContactDo {
	return g.Clauses(dbresolver.Write)
}

func (g groupContactDo) Session(config *gorm.Session) IGroupContactDo {
	return g.withDO(g.DO.Session(config))
}

func (g groupContactDo) Clauses(conds ...clause.Expression) IGroupContactDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g groupContactDo) Returning(value interface{}, columns ...string) IGroupContactDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g groupContactDo) Not(conds ...gen.Condition) IGroupContactDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g groupContactDo) Or(conds ...gen.Condition) IGroupContactDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g groupContactDo) Select(conds ...field.Expr) IGroupContactDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g groupContactDo) Where(conds ...gen.Condition) IGroupContactDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g groupContactDo) Order(conds ...field.Expr) IGroupContactDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g groupContactDo) Distinct(cols ...field.Expr) IGroupContactDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g groupContactDo) Omit(cols ...field.Expr) IGroupContactDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g groupContactDo) Join(table schema.Tabler, on ...field.Expr) IGroupContactDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g groupContactDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGroupContactDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g groupContactDo) RightJoin(table schema.Tabler, on ...field.Expr) IGroupContactDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g groupContactDo) Group(cols ...field.Expr) IGroupContactDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g groupContactDo) Having(conds ...gen.Condition) IGroupContactDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g groupContactDo) Limit(limit int) IGroupContactDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g groupContactDo) Offset(offset int) IGroupContactDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g groupContactDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGroupContactDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g groupContactDo) Unscoped() IGroupContactDo {
	return g.withDO(g.DO.Unscoped())
}

func (g groupContactDo) Create(values ...*model.GroupContact) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g groupContactDo) CreateInBatches(values []*model.GroupContact, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g groupContactDo) Save(values ...*model.GroupContact) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g groupContactDo) First() (*model.GroupContact, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupContact), nil
	}
}

func (g groupContactDo) Take() (*model.GroupContact, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupContact), nil
	}
}

func (g groupContactDo) Last() (*model.GroupContact, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupContact), nil
	}
}

func (g groupContactDo) Find() ([]*model.GroupContact, error) {
	result, err := g.DO.Find()
	return result.([]*model.GroupContact), err
}

func (g groupContactDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GroupContact, err error) {
	buf := make([]*model.GroupContact, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g groupContactDo) FindInBatches(result *[]*model.GroupContact, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g groupContactDo) Attrs(attrs ...field.AssignExpr) IGroupContactDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g groupContactDo) Assign(attrs ...field.AssignExpr) IGroupContactDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g groupContactDo) Joins(fields ...field.RelationField) IGroupContactDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g groupContactDo) Preload(fields ...field.RelationField) IGroupContactDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g groupContactDo) FirstOrInit() (*model.GroupContact, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupContact), nil
	}
}

func (g groupContactDo) FirstOrCreate() (*model.GroupContact, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupContact), nil
	}
}

func (g groupContactDo) FindByPage(offset int, limit int) (result []*model.GroupContact, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g groupContactDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g groupContactDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g groupContactDo) Delete(models ...*model.GroupContact) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *groupContactDo) withDO(do gen.Dao) *groupContactDo {
	g.DO = *do.(*gen.DO)
	return g
}
