// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package group

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HarryWang29/echo_mind/internal/infra/db/sqlite/model"
)

func newGroupMember(db *gorm.DB, opts ...gen.DOOption) groupMember {
	_groupMember := groupMember{}

	_groupMember.groupMemberDo.UseDB(db, opts...)
	_groupMember.groupMemberDo.UseModel(&model.GroupMember{})

	tableName := _groupMember.groupMemberDo.TableName()
	_groupMember.ALL = field.NewAsterisk(tableName)
	_groupMember.MNsUsrName = field.NewString(tableName, "m_nsUsrName")
	_groupMember.MUIConType = field.NewInt32(tableName, "m_uiConType")
	_groupMember.Nickname = field.NewString(tableName, "nickname")
	_groupMember.MNsFullPY = field.NewString(tableName, "m_nsFullPY")
	_groupMember.MNsShortPY = field.NewString(tableName, "m_nsShortPY")
	_groupMember.MNsRemark = field.NewString(tableName, "m_nsRemark")
	_groupMember.MNsRemarkPYFull = field.NewString(tableName, "m_nsRemarkPYFull")
	_groupMember.MNsRemarkPYShort = field.NewString(tableName, "m_nsRemarkPYShort")
	_groupMember.MUICertificationFlag = field.NewInt32(tableName, "m_uiCertificationFlag")
	_groupMember.MUISex = field.NewInt32(tableName, "m_uiSex")
	_groupMember.MUIType = field.NewInt32(tableName, "m_uiType")
	_groupMember.MNsImgStatus = field.NewString(tableName, "m_nsImgStatus")
	_groupMember.MUIImgKey = field.NewInt32(tableName, "m_uiImgKey")
	_groupMember.MNsHeadImgURL = field.NewString(tableName, "m_nsHeadImgUrl")
	_groupMember.MNsHeadHDImgURL = field.NewString(tableName, "m_nsHeadHDImgUrl")
	_groupMember.MNsHeadHDMd5 = field.NewString(tableName, "m_nsHeadHDMd5")
	_groupMember.MNsChatRoomMemList = field.NewString(tableName, "m_nsChatRoomMemList")
	_groupMember.MNsChatRoomAdminList = field.NewString(tableName, "m_nsChatRoomAdminList")
	_groupMember.MUIChatRoomStatus = field.NewInt32(tableName, "m_uiChatRoomStatus")
	_groupMember.MNsChatRoomDesc = field.NewString(tableName, "m_nsChatRoomDesc")
	_groupMember.MNsDraft = field.NewString(tableName, "m_nsDraft")
	_groupMember.MNsBrandIconURL = field.NewString(tableName, "m_nsBrandIconUrl")
	_groupMember.MNsGoogleContactName = field.NewString(tableName, "m_nsGoogleContactName")
	_groupMember.MNsAliasName = field.NewString(tableName, "m_nsAliasName")
	_groupMember.MNsEncodeUserName = field.NewString(tableName, "m_nsEncodeUserName")
	_groupMember.MUIChatRoomVersion = field.NewInt32(tableName, "m_uiChatRoomVersion")
	_groupMember.MUIChatRoomMaxCount = field.NewInt32(tableName, "m_uiChatRoomMaxCount")
	_groupMember.MUIChatRoomType = field.NewInt32(tableName, "m_uiChatRoomType")
	_groupMember.MPatSuffix = field.NewString(tableName, "m_patSuffix")
	_groupMember.RichChatRoomDesc = field.NewString(tableName, "richChatRoomDesc")
	_groupMember.PackedWCContactData = field.NewBytes(tableName, "_packed_WCContactData")
	_groupMember.OpenIMInfo = field.NewBytes(tableName, "openIMInfo")

	_groupMember.fillFieldMap()

	return _groupMember
}

type groupMember struct {
	groupMemberDo

	ALL                  field.Asterisk
	MNsUsrName           field.String
	MUIConType           field.Int32
	Nickname             field.String
	MNsFullPY            field.String
	MNsShortPY           field.String
	MNsRemark            field.String
	MNsRemarkPYFull      field.String
	MNsRemarkPYShort     field.String
	MUICertificationFlag field.Int32
	MUISex               field.Int32
	MUIType              field.Int32
	MNsImgStatus         field.String
	MUIImgKey            field.Int32
	MNsHeadImgURL        field.String
	MNsHeadHDImgURL      field.String
	MNsHeadHDMd5         field.String
	MNsChatRoomMemList   field.String
	MNsChatRoomAdminList field.String
	MUIChatRoomStatus    field.Int32
	MNsChatRoomDesc      field.String
	MNsDraft             field.String
	MNsBrandIconURL      field.String
	MNsGoogleContactName field.String
	MNsAliasName         field.String
	MNsEncodeUserName    field.String
	MUIChatRoomVersion   field.Int32
	MUIChatRoomMaxCount  field.Int32
	MUIChatRoomType      field.Int32
	MPatSuffix           field.String
	RichChatRoomDesc     field.String
	PackedWCContactData  field.Bytes
	OpenIMInfo           field.Bytes

	fieldMap map[string]field.Expr
}

func (g groupMember) Table(newTableName string) *groupMember {
	g.groupMemberDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g groupMember) As(alias string) *groupMember {
	g.groupMemberDo.DO = *(g.groupMemberDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *groupMember) updateTableName(table string) *groupMember {
	g.ALL = field.NewAsterisk(table)
	g.MNsUsrName = field.NewString(table, "m_nsUsrName")
	g.MUIConType = field.NewInt32(table, "m_uiConType")
	g.Nickname = field.NewString(table, "nickname")
	g.MNsFullPY = field.NewString(table, "m_nsFullPY")
	g.MNsShortPY = field.NewString(table, "m_nsShortPY")
	g.MNsRemark = field.NewString(table, "m_nsRemark")
	g.MNsRemarkPYFull = field.NewString(table, "m_nsRemarkPYFull")
	g.MNsRemarkPYShort = field.NewString(table, "m_nsRemarkPYShort")
	g.MUICertificationFlag = field.NewInt32(table, "m_uiCertificationFlag")
	g.MUISex = field.NewInt32(table, "m_uiSex")
	g.MUIType = field.NewInt32(table, "m_uiType")
	g.MNsImgStatus = field.NewString(table, "m_nsImgStatus")
	g.MUIImgKey = field.NewInt32(table, "m_uiImgKey")
	g.MNsHeadImgURL = field.NewString(table, "m_nsHeadImgUrl")
	g.MNsHeadHDImgURL = field.NewString(table, "m_nsHeadHDImgUrl")
	g.MNsHeadHDMd5 = field.NewString(table, "m_nsHeadHDMd5")
	g.MNsChatRoomMemList = field.NewString(table, "m_nsChatRoomMemList")
	g.MNsChatRoomAdminList = field.NewString(table, "m_nsChatRoomAdminList")
	g.MUIChatRoomStatus = field.NewInt32(table, "m_uiChatRoomStatus")
	g.MNsChatRoomDesc = field.NewString(table, "m_nsChatRoomDesc")
	g.MNsDraft = field.NewString(table, "m_nsDraft")
	g.MNsBrandIconURL = field.NewString(table, "m_nsBrandIconUrl")
	g.MNsGoogleContactName = field.NewString(table, "m_nsGoogleContactName")
	g.MNsAliasName = field.NewString(table, "m_nsAliasName")
	g.MNsEncodeUserName = field.NewString(table, "m_nsEncodeUserName")
	g.MUIChatRoomVersion = field.NewInt32(table, "m_uiChatRoomVersion")
	g.MUIChatRoomMaxCount = field.NewInt32(table, "m_uiChatRoomMaxCount")
	g.MUIChatRoomType = field.NewInt32(table, "m_uiChatRoomType")
	g.MPatSuffix = field.NewString(table, "m_patSuffix")
	g.RichChatRoomDesc = field.NewString(table, "richChatRoomDesc")
	g.PackedWCContactData = field.NewBytes(table, "_packed_WCContactData")
	g.OpenIMInfo = field.NewBytes(table, "openIMInfo")

	g.fillFieldMap()

	return g
}

func (g *groupMember) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *groupMember) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 32)
	g.fieldMap["m_nsUsrName"] = g.MNsUsrName
	g.fieldMap["m_uiConType"] = g.MUIConType
	g.fieldMap["nickname"] = g.Nickname
	g.fieldMap["m_nsFullPY"] = g.MNsFullPY
	g.fieldMap["m_nsShortPY"] = g.MNsShortPY
	g.fieldMap["m_nsRemark"] = g.MNsRemark
	g.fieldMap["m_nsRemarkPYFull"] = g.MNsRemarkPYFull
	g.fieldMap["m_nsRemarkPYShort"] = g.MNsRemarkPYShort
	g.fieldMap["m_uiCertificationFlag"] = g.MUICertificationFlag
	g.fieldMap["m_uiSex"] = g.MUISex
	g.fieldMap["m_uiType"] = g.MUIType
	g.fieldMap["m_nsImgStatus"] = g.MNsImgStatus
	g.fieldMap["m_uiImgKey"] = g.MUIImgKey
	g.fieldMap["m_nsHeadImgUrl"] = g.MNsHeadImgURL
	g.fieldMap["m_nsHeadHDImgUrl"] = g.MNsHeadHDImgURL
	g.fieldMap["m_nsHeadHDMd5"] = g.MNsHeadHDMd5
	g.fieldMap["m_nsChatRoomMemList"] = g.MNsChatRoomMemList
	g.fieldMap["m_nsChatRoomAdminList"] = g.MNsChatRoomAdminList
	g.fieldMap["m_uiChatRoomStatus"] = g.MUIChatRoomStatus
	g.fieldMap["m_nsChatRoomDesc"] = g.MNsChatRoomDesc
	g.fieldMap["m_nsDraft"] = g.MNsDraft
	g.fieldMap["m_nsBrandIconUrl"] = g.MNsBrandIconURL
	g.fieldMap["m_nsGoogleContactName"] = g.MNsGoogleContactName
	g.fieldMap["m_nsAliasName"] = g.MNsAliasName
	g.fieldMap["m_nsEncodeUserName"] = g.MNsEncodeUserName
	g.fieldMap["m_uiChatRoomVersion"] = g.MUIChatRoomVersion
	g.fieldMap["m_uiChatRoomMaxCount"] = g.MUIChatRoomMaxCount
	g.fieldMap["m_uiChatRoomType"] = g.MUIChatRoomType
	g.fieldMap["m_patSuffix"] = g.MPatSuffix
	g.fieldMap["richChatRoomDesc"] = g.RichChatRoomDesc
	g.fieldMap["_packed_WCContactData"] = g.PackedWCContactData
	g.fieldMap["openIMInfo"] = g.OpenIMInfo
}

func (g groupMember) clone(db *gorm.DB) groupMember {
	g.groupMemberDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g groupMember) replaceDB(db *gorm.DB) groupMember {
	g.groupMemberDo.ReplaceDB(db)
	return g
}

type groupMemberDo struct{ gen.DO }

type IGroupMemberDo interface {
	gen.SubQuery
	Debug() IGroupMemberDo
	WithContext(ctx context.Context) IGroupMemberDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGroupMemberDo
	WriteDB() IGroupMemberDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGroupMemberDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGroupMemberDo
	Not(conds ...gen.Condition) IGroupMemberDo
	Or(conds ...gen.Condition) IGroupMemberDo
	Select(conds ...field.Expr) IGroupMemberDo
	Where(conds ...gen.Condition) IGroupMemberDo
	Order(conds ...field.Expr) IGroupMemberDo
	Distinct(cols ...field.Expr) IGroupMemberDo
	Omit(cols ...field.Expr) IGroupMemberDo
	Join(table schema.Tabler, on ...field.Expr) IGroupMemberDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGroupMemberDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGroupMemberDo
	Group(cols ...field.Expr) IGroupMemberDo
	Having(conds ...gen.Condition) IGroupMemberDo
	Limit(limit int) IGroupMemberDo
	Offset(offset int) IGroupMemberDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGroupMemberDo
	Unscoped() IGroupMemberDo
	Create(values ...*model.GroupMember) error
	CreateInBatches(values []*model.GroupMember, batchSize int) error
	Save(values ...*model.GroupMember) error
	First() (*model.GroupMember, error)
	Take() (*model.GroupMember, error)
	Last() (*model.GroupMember, error)
	Find() ([]*model.GroupMember, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GroupMember, err error)
	FindInBatches(result *[]*model.GroupMember, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GroupMember) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGroupMemberDo
	Assign(attrs ...field.AssignExpr) IGroupMemberDo
	Joins(fields ...field.RelationField) IGroupMemberDo
	Preload(fields ...field.RelationField) IGroupMemberDo
	FirstOrInit() (*model.GroupMember, error)
	FirstOrCreate() (*model.GroupMember, error)
	FindByPage(offset int, limit int) (result []*model.GroupMember, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGroupMemberDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	GetByID(id int) (result model.GroupMember, err error)
}

// SELECT * FROM @@table WHERE id=@id
func (g groupMemberDo) GetByID(id int) (result model.GroupMember, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("SELECT * FROM GroupMember WHERE id=? ")

	var executeSQL *gorm.DB
	executeSQL = g.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (g groupMemberDo) Debug() IGroupMemberDo {
	return g.withDO(g.DO.Debug())
}

func (g groupMemberDo) WithContext(ctx context.Context) IGroupMemberDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g groupMemberDo) ReadDB() IGroupMemberDo {
	return g.Clauses(dbresolver.Read)
}

func (g groupMemberDo) WriteDB() IGroupMemberDo {
	return g.Clauses(dbresolver.Write)
}

func (g groupMemberDo) Session(config *gorm.Session) IGroupMemberDo {
	return g.withDO(g.DO.Session(config))
}

func (g groupMemberDo) Clauses(conds ...clause.Expression) IGroupMemberDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g groupMemberDo) Returning(value interface{}, columns ...string) IGroupMemberDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g groupMemberDo) Not(conds ...gen.Condition) IGroupMemberDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g groupMemberDo) Or(conds ...gen.Condition) IGroupMemberDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g groupMemberDo) Select(conds ...field.Expr) IGroupMemberDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g groupMemberDo) Where(conds ...gen.Condition) IGroupMemberDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g groupMemberDo) Order(conds ...field.Expr) IGroupMemberDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g groupMemberDo) Distinct(cols ...field.Expr) IGroupMemberDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g groupMemberDo) Omit(cols ...field.Expr) IGroupMemberDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g groupMemberDo) Join(table schema.Tabler, on ...field.Expr) IGroupMemberDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g groupMemberDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGroupMemberDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g groupMemberDo) RightJoin(table schema.Tabler, on ...field.Expr) IGroupMemberDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g groupMemberDo) Group(cols ...field.Expr) IGroupMemberDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g groupMemberDo) Having(conds ...gen.Condition) IGroupMemberDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g groupMemberDo) Limit(limit int) IGroupMemberDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g groupMemberDo) Offset(offset int) IGroupMemberDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g groupMemberDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGroupMemberDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g groupMemberDo) Unscoped() IGroupMemberDo {
	return g.withDO(g.DO.Unscoped())
}

func (g groupMemberDo) Create(values ...*model.GroupMember) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g groupMemberDo) CreateInBatches(values []*model.GroupMember, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g groupMemberDo) Save(values ...*model.GroupMember) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g groupMemberDo) First() (*model.GroupMember, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupMember), nil
	}
}

func (g groupMemberDo) Take() (*model.GroupMember, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupMember), nil
	}
}

func (g groupMemberDo) Last() (*model.GroupMember, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupMember), nil
	}
}

func (g groupMemberDo) Find() ([]*model.GroupMember, error) {
	result, err := g.DO.Find()
	return result.([]*model.GroupMember), err
}

func (g groupMemberDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GroupMember, err error) {
	buf := make([]*model.GroupMember, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g groupMemberDo) FindInBatches(result *[]*model.GroupMember, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g groupMemberDo) Attrs(attrs ...field.AssignExpr) IGroupMemberDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g groupMemberDo) Assign(attrs ...field.AssignExpr) IGroupMemberDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g groupMemberDo) Joins(fields ...field.RelationField) IGroupMemberDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g groupMemberDo) Preload(fields ...field.RelationField) IGroupMemberDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g groupMemberDo) FirstOrInit() (*model.GroupMember, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupMember), nil
	}
}

func (g groupMemberDo) FirstOrCreate() (*model.GroupMember, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupMember), nil
	}
}

func (g groupMemberDo) FindByPage(offset int, limit int) (result []*model.GroupMember, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g groupMemberDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g groupMemberDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g groupMemberDo) Delete(models ...*model.GroupMember) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *groupMemberDo) withDO(do gen.Dao) *groupMemberDo {
	g.DO = *do.(*gen.DO)
	return g
}
