// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package session

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HarryWang29/echo_mind/internal/infra/db/sqlite/model"
)

func newSessionAbstractBrand(db *gorm.DB, opts ...gen.DOOption) sessionAbstractBrand {
	_sessionAbstractBrand := sessionAbstractBrand{}

	_sessionAbstractBrand.sessionAbstractBrandDo.UseDB(db, opts...)
	_sessionAbstractBrand.sessionAbstractBrandDo.UseModel(&model.SessionAbstractBrand{})

	tableName := _sessionAbstractBrand.sessionAbstractBrandDo.TableName()
	_sessionAbstractBrand.ALL = field.NewAsterisk(tableName)
	_sessionAbstractBrand.MNsUserName = field.NewString(tableName, "m_nsUserName")
	_sessionAbstractBrand.MUUnReadCount = field.NewInt32(tableName, "m_uUnReadCount")
	_sessionAbstractBrand.MBShowUnReadAsRedDot = field.NewInt32(tableName, "m_bShowUnReadAsRedDot")
	_sessionAbstractBrand.MBMarkUnread = field.NewInt32(tableName, "m_bMarkUnread")
	_sessionAbstractBrand.MULastTime = field.NewInt32(tableName, "m_uLastTime")
	_sessionAbstractBrand.StrRes1 = field.NewString(tableName, "strRes1")
	_sessionAbstractBrand.StrRes2 = field.NewString(tableName, "strRes2")
	_sessionAbstractBrand.StrRes3 = field.NewString(tableName, "strRes3")
	_sessionAbstractBrand.IntRes1 = field.NewInt32(tableName, "intRes1")
	_sessionAbstractBrand.IntRes2 = field.NewInt32(tableName, "intRes2")
	_sessionAbstractBrand.IntRes3 = field.NewInt32(tableName, "intRes3")
	_sessionAbstractBrand.PackedMMSessionInfo = field.NewBytes(tableName, "_packed_MMSessionInfo")

	_sessionAbstractBrand.fillFieldMap()

	return _sessionAbstractBrand
}

type sessionAbstractBrand struct {
	sessionAbstractBrandDo

	ALL                  field.Asterisk
	MNsUserName          field.String
	MUUnReadCount        field.Int32
	MBShowUnReadAsRedDot field.Int32
	MBMarkUnread         field.Int32
	MULastTime           field.Int32
	StrRes1              field.String
	StrRes2              field.String
	StrRes3              field.String
	IntRes1              field.Int32
	IntRes2              field.Int32
	IntRes3              field.Int32
	PackedMMSessionInfo  field.Bytes

	fieldMap map[string]field.Expr
}

func (s sessionAbstractBrand) Table(newTableName string) *sessionAbstractBrand {
	s.sessionAbstractBrandDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sessionAbstractBrand) As(alias string) *sessionAbstractBrand {
	s.sessionAbstractBrandDo.DO = *(s.sessionAbstractBrandDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sessionAbstractBrand) updateTableName(table string) *sessionAbstractBrand {
	s.ALL = field.NewAsterisk(table)
	s.MNsUserName = field.NewString(table, "m_nsUserName")
	s.MUUnReadCount = field.NewInt32(table, "m_uUnReadCount")
	s.MBShowUnReadAsRedDot = field.NewInt32(table, "m_bShowUnReadAsRedDot")
	s.MBMarkUnread = field.NewInt32(table, "m_bMarkUnread")
	s.MULastTime = field.NewInt32(table, "m_uLastTime")
	s.StrRes1 = field.NewString(table, "strRes1")
	s.StrRes2 = field.NewString(table, "strRes2")
	s.StrRes3 = field.NewString(table, "strRes3")
	s.IntRes1 = field.NewInt32(table, "intRes1")
	s.IntRes2 = field.NewInt32(table, "intRes2")
	s.IntRes3 = field.NewInt32(table, "intRes3")
	s.PackedMMSessionInfo = field.NewBytes(table, "_packed_MMSessionInfo")

	s.fillFieldMap()

	return s
}

func (s *sessionAbstractBrand) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sessionAbstractBrand) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 12)
	s.fieldMap["m_nsUserName"] = s.MNsUserName
	s.fieldMap["m_uUnReadCount"] = s.MUUnReadCount
	s.fieldMap["m_bShowUnReadAsRedDot"] = s.MBShowUnReadAsRedDot
	s.fieldMap["m_bMarkUnread"] = s.MBMarkUnread
	s.fieldMap["m_uLastTime"] = s.MULastTime
	s.fieldMap["strRes1"] = s.StrRes1
	s.fieldMap["strRes2"] = s.StrRes2
	s.fieldMap["strRes3"] = s.StrRes3
	s.fieldMap["intRes1"] = s.IntRes1
	s.fieldMap["intRes2"] = s.IntRes2
	s.fieldMap["intRes3"] = s.IntRes3
	s.fieldMap["_packed_MMSessionInfo"] = s.PackedMMSessionInfo
}

func (s sessionAbstractBrand) clone(db *gorm.DB) sessionAbstractBrand {
	s.sessionAbstractBrandDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sessionAbstractBrand) replaceDB(db *gorm.DB) sessionAbstractBrand {
	s.sessionAbstractBrandDo.ReplaceDB(db)
	return s
}

type sessionAbstractBrandDo struct{ gen.DO }

type ISessionAbstractBrandDo interface {
	gen.SubQuery
	Debug() ISessionAbstractBrandDo
	WithContext(ctx context.Context) ISessionAbstractBrandDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISessionAbstractBrandDo
	WriteDB() ISessionAbstractBrandDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISessionAbstractBrandDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISessionAbstractBrandDo
	Not(conds ...gen.Condition) ISessionAbstractBrandDo
	Or(conds ...gen.Condition) ISessionAbstractBrandDo
	Select(conds ...field.Expr) ISessionAbstractBrandDo
	Where(conds ...gen.Condition) ISessionAbstractBrandDo
	Order(conds ...field.Expr) ISessionAbstractBrandDo
	Distinct(cols ...field.Expr) ISessionAbstractBrandDo
	Omit(cols ...field.Expr) ISessionAbstractBrandDo
	Join(table schema.Tabler, on ...field.Expr) ISessionAbstractBrandDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISessionAbstractBrandDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISessionAbstractBrandDo
	Group(cols ...field.Expr) ISessionAbstractBrandDo
	Having(conds ...gen.Condition) ISessionAbstractBrandDo
	Limit(limit int) ISessionAbstractBrandDo
	Offset(offset int) ISessionAbstractBrandDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISessionAbstractBrandDo
	Unscoped() ISessionAbstractBrandDo
	Create(values ...*model.SessionAbstractBrand) error
	CreateInBatches(values []*model.SessionAbstractBrand, batchSize int) error
	Save(values ...*model.SessionAbstractBrand) error
	First() (*model.SessionAbstractBrand, error)
	Take() (*model.SessionAbstractBrand, error)
	Last() (*model.SessionAbstractBrand, error)
	Find() ([]*model.SessionAbstractBrand, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SessionAbstractBrand, err error)
	FindInBatches(result *[]*model.SessionAbstractBrand, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SessionAbstractBrand) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISessionAbstractBrandDo
	Assign(attrs ...field.AssignExpr) ISessionAbstractBrandDo
	Joins(fields ...field.RelationField) ISessionAbstractBrandDo
	Preload(fields ...field.RelationField) ISessionAbstractBrandDo
	FirstOrInit() (*model.SessionAbstractBrand, error)
	FirstOrCreate() (*model.SessionAbstractBrand, error)
	FindByPage(offset int, limit int) (result []*model.SessionAbstractBrand, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISessionAbstractBrandDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	GetByID(id int) (result model.SessionAbstractBrand, err error)
}

// SELECT * FROM @@table WHERE id=@id
func (s sessionAbstractBrandDo) GetByID(id int) (result model.SessionAbstractBrand, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("SELECT * FROM SessionAbstractBrand WHERE id=? ")

	var executeSQL *gorm.DB
	executeSQL = s.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (s sessionAbstractBrandDo) Debug() ISessionAbstractBrandDo {
	return s.withDO(s.DO.Debug())
}

func (s sessionAbstractBrandDo) WithContext(ctx context.Context) ISessionAbstractBrandDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sessionAbstractBrandDo) ReadDB() ISessionAbstractBrandDo {
	return s.Clauses(dbresolver.Read)
}

func (s sessionAbstractBrandDo) WriteDB() ISessionAbstractBrandDo {
	return s.Clauses(dbresolver.Write)
}

func (s sessionAbstractBrandDo) Session(config *gorm.Session) ISessionAbstractBrandDo {
	return s.withDO(s.DO.Session(config))
}

func (s sessionAbstractBrandDo) Clauses(conds ...clause.Expression) ISessionAbstractBrandDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sessionAbstractBrandDo) Returning(value interface{}, columns ...string) ISessionAbstractBrandDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sessionAbstractBrandDo) Not(conds ...gen.Condition) ISessionAbstractBrandDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sessionAbstractBrandDo) Or(conds ...gen.Condition) ISessionAbstractBrandDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sessionAbstractBrandDo) Select(conds ...field.Expr) ISessionAbstractBrandDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sessionAbstractBrandDo) Where(conds ...gen.Condition) ISessionAbstractBrandDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sessionAbstractBrandDo) Order(conds ...field.Expr) ISessionAbstractBrandDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sessionAbstractBrandDo) Distinct(cols ...field.Expr) ISessionAbstractBrandDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sessionAbstractBrandDo) Omit(cols ...field.Expr) ISessionAbstractBrandDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sessionAbstractBrandDo) Join(table schema.Tabler, on ...field.Expr) ISessionAbstractBrandDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sessionAbstractBrandDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISessionAbstractBrandDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sessionAbstractBrandDo) RightJoin(table schema.Tabler, on ...field.Expr) ISessionAbstractBrandDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sessionAbstractBrandDo) Group(cols ...field.Expr) ISessionAbstractBrandDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sessionAbstractBrandDo) Having(conds ...gen.Condition) ISessionAbstractBrandDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sessionAbstractBrandDo) Limit(limit int) ISessionAbstractBrandDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sessionAbstractBrandDo) Offset(offset int) ISessionAbstractBrandDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sessionAbstractBrandDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISessionAbstractBrandDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sessionAbstractBrandDo) Unscoped() ISessionAbstractBrandDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sessionAbstractBrandDo) Create(values ...*model.SessionAbstractBrand) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sessionAbstractBrandDo) CreateInBatches(values []*model.SessionAbstractBrand, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sessionAbstractBrandDo) Save(values ...*model.SessionAbstractBrand) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sessionAbstractBrandDo) First() (*model.SessionAbstractBrand, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SessionAbstractBrand), nil
	}
}

func (s sessionAbstractBrandDo) Take() (*model.SessionAbstractBrand, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SessionAbstractBrand), nil
	}
}

func (s sessionAbstractBrandDo) Last() (*model.SessionAbstractBrand, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SessionAbstractBrand), nil
	}
}

func (s sessionAbstractBrandDo) Find() ([]*model.SessionAbstractBrand, error) {
	result, err := s.DO.Find()
	return result.([]*model.SessionAbstractBrand), err
}

func (s sessionAbstractBrandDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SessionAbstractBrand, err error) {
	buf := make([]*model.SessionAbstractBrand, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sessionAbstractBrandDo) FindInBatches(result *[]*model.SessionAbstractBrand, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sessionAbstractBrandDo) Attrs(attrs ...field.AssignExpr) ISessionAbstractBrandDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sessionAbstractBrandDo) Assign(attrs ...field.AssignExpr) ISessionAbstractBrandDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sessionAbstractBrandDo) Joins(fields ...field.RelationField) ISessionAbstractBrandDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sessionAbstractBrandDo) Preload(fields ...field.RelationField) ISessionAbstractBrandDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sessionAbstractBrandDo) FirstOrInit() (*model.SessionAbstractBrand, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SessionAbstractBrand), nil
	}
}

func (s sessionAbstractBrandDo) FirstOrCreate() (*model.SessionAbstractBrand, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SessionAbstractBrand), nil
	}
}

func (s sessionAbstractBrandDo) FindByPage(offset int, limit int) (result []*model.SessionAbstractBrand, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sessionAbstractBrandDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sessionAbstractBrandDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sessionAbstractBrandDo) Delete(models ...*model.SessionAbstractBrand) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sessionAbstractBrandDo) withDO(do gen.Dao) *sessionAbstractBrandDo {
	s.DO = *do.(*gen.DO)
	return s
}
